name: 프론트 이미지 빌드 및 Docker Hub에 Push

on:
  push:
    branches: [ main ]  # main 브랜치에 push 될 때 작동

env:
  IMAGE_NAME: front                         # 원하는 이미지 이름 (레포 이름과 같게 설정 추천)
  IMAGE_TAG: ${{ github.sha }}             # 커밋 SHA를 이미지 태그로 사용

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Docker logout (optional cleanup)
        if: always()
        run: docker logout
